name: Test macro feature

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - README
      - NEWS

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    name: Test macro feature

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev
    - name: Autogen && configure
      run: |
        ./autogen.sh
        ./configure --enable-macros
    - name: Make
      run: make
    - name: Make check
      run: make check
    - name: Store the test log
      if: ${{ always() }} # store the test log even if the tests failed
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: test-suite-macro.log
        path: tests/test-suite.log
