name: Make check

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - README
      - NEWS
  pull_request:
    branches: [ master ]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    name: Build with ${{ matrix.ucs }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true # do not compile for ucs4 if ucs2 fails
      matrix:
        ucs: [ucs2, ucs4]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev texinfo texlive
    - name: Autogen
      run: ./autogen.sh
    - name: Configure
      run: ./configure
      if: matrix.ucs == 'ucs2'
    - name: Configure with ucs4
      run: ./configure --enable-ucs4
      if: matrix.ucs == 'ucs4'
    - name: Make check
      run: make check
    - name: Store the test suite log
      if: ${{ always() }} # store the test suite log even if the tests failed
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: test-suite-${{ matrix.ucs }}.log
        path: tests/test-suite.log
